### ISSUE TITLE
Maximum recursion depth exceeded in comparison, foundry + erigon

### ISSUE THREAD

**Issue by milkyklim** [ApeWorX/ape#1216]
### Environment information

- OS: macOS 
- Python Version: Python 3.8.6
- `ape` and plugin versions:

```sh
$ ape --version
0.5.9

$ ape plugins list
Installed Plugins:
  template     0.5.0
  vyper        0.5.2
  ens          0.5.1
  solidity     0.5.4
  tokens       0.1.0b5.dev2+g9dc883e
  hardhat      0.5.4
  fantom       0.5.1
  foundry      0.5.2
```

- Contents of your `ape-config.yaml`: 

```sh
$ cat ape-config.yaml
name: nft
plugins:
  - name: vyper
  - name: solidity
  - name: tokens
  - name: ethereum
  - name: foundry
  - name: ens
ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry
foundry:
  port: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: geth
geth:
  ethereum:
    mainnet:
      uri: ${WEB3_PROVIDER_URI}
```

### What went wrong?

I try to run:

```sh
ape test  -s --gas --verbosity DEBUG
```

But then I get about 20mb of error traces. I put some parts here: 
https://gist.github.com/milkyklim/01863a89033ac5ea1f11ede4e295fbf6

Essentially foundry + erigon setup returns `E   RecursionError: maximum recursion depth exceeded in comparison`.

I managed to narrow down the scope –  it's the `--gas` flag that breaks everything cause without it tests run as expected.

**Comment by fubuloubu** [comment]
Might be getting stuck in the check for a Safe-style proxy added in #1178 because it's making a view call, but with `--gas` active it turns view calls into transactions in order to determine the gas usage, which requires checking for the contract type, which checks for proxy type, continuing the cycle until stack dump

**Comment by antazoey** [comment]
Sorry for being super late at responding!

The bug is that it was trying to trace the calls made during proxy checking, which it did by sending them as txns.

This got fixed on this PR: https://github.com/ApeWorX/ape/pull/1131 (and some other adjustments of similar nature on following PRs) by skipping traces on all proxy-call checks.

Related, Foundry and hardhat no longer send calls as tx to get gas, now that `debug_traceCall` is implemented.

So because of all the fixes, this should no longer be a problem.
