### ISSUE TITLE
Network Manager is not Fault Tolerant with External Plugins

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#125]
### What went wrong?
```bash
$ ape plugins add infura
INFO: Installing ape_infura...
$ ape
WARNING: Error loading cli endpoint for plugin 'ape_console'
WARNING: Error loading cli endpoint for plugin 'ape_run'
Usage: ape [OPTIONS] COMMAND [ARGS]...
```

### How can it be fixed?
These CLI endpoints use the `networks` object from `ape` core to produce the `--network` option. This method should be fault tolerant of issues in external plugins.

**Comment by unparalleled-js** [comment]
This issue seems to be fixed! Not sure how though.

Probably related to some of the `--network` option refactoring that happened last fall.

But, to test that it is fixed, install `ape-infura` locally from source. Break it on purpose (Add a bunch of random text to the top of the file). Then, run `ape console` using any other network... It works just fine! Wahoo!
