### ISSUE TITLE
`EcosystemAPI.decode_receipt` makes erronous calls to `Provider.chain_id` [APE-635]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1304]
### What went wrong?

I noticed that every time you call `EcosystemAPI.decode_receipt` is certain scenarios where the transaction class does not have `"chainid"` field in the structured transaction, the ecosystem will query `Provider.chain_id` to obtain the right value for chain ID. It actually happens in a lot of scenarios that calls are made to obtain this property, and it will almost never change for a connected `ProviderAPI` subclass

### How can it be fixed?

`ProviderAPI.chain_id` can probably be a `cached_property`, which would eliminate this issue

**Comment by unparalleled-js** [comment]
isnt it already cached in web3.py?

**Comment by unparalleled-js** [comment]
Also we are already caching it here: https://github.com/ApeWorX/ape/blob/main/src/ape/api/providers.py#L133-L134
We have been since this PR: https://github.com/ApeWorX/ape/pull/683/files

So if the calls happen, it is not from Ape but perhaps internal to Web3.py. You still see those requests in the logs

however, IICR, web3.py actually caches these already.

Can we close this issue or is there something else to do here?

**Comment by unparalleled-js** [comment]
web3.py still logs cached requests, so if they happen internal to that lib, and it calls it, youll still see it

**Comment by unparalleled-js** [comment]
fixed by https://github.com/ApeWorX/ape/pull/1375 ?

**Comment by fubuloubu** [comment]
> fixed by #1375 ?

I got this issue by calling a large query with the Etherscan engine w/ DEBUG:
https://github.com/ApeWorX/ape-etherscan/blob/134efd1b80adb9759a44d2235cb65ed9d3aa7351/ape_etherscan/query.py#L62
