### ISSUE TITLE
Bug: docker container requires chown for project dir [APE-716]

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#1340]
This shouldn't: https://github.com/ApeWorX/ape/issues/1336#issuecomment-1469075527

**Comment by sabotagebeats** [comment]
trying to replicate this but it doesn't seem to be a problem when using: 
`docker run --volume $HOME/.ape:/home/harambe/.ape --volume $HOME/.vvm:/home/harambe/.vvm --volume $HOME/.solcx:/home/harambe/.solcx --volume $PWD:/home/harambe/project --workdir /home/harambe/project apeworx/ape:latest compile -f`:
```
INFO: Compiling 'SafeMath.sol'.
INFO: Compiling 'payable.sol'.
INFO: Compiling 'string.sol'.
INFO: Compiling 'GenerativeNFT.sol'.
INFO: Compiling 'Token.sol'.
```

**Comment by sabotagebeats** [comment]
@PoCk3T-SPAI I'm trying to replicate this issue here but I seem to be unable to. I'm going to try it with your dockerfile you posted in the other issue.

**Comment by sabotagebeats** [comment]
unable to replicate with this Dockerfile: 
```
FROM apeworx/ape:latest

RUN ape plugins install \
    polygon \
    bsc \
    avalanche \
    arbitrum \
    optimism \
    fantom \
    starknet \
    solidity \
    alchemy \
    infura \
    etherscan \
    --upgrade
```

**Comment by sabotagebeats** [comment]
unable to replicate with this Dockerfile: 
```
FROM apeworx/ape:latest

USER root

RUN apt-get update \
    && apt-get install -y \
    --no-install-recommends -o \
    APT::Immediate-Configure=false \
    gcc g++ git
    
RUN ape plugins install \
    polygon \
    bsc \
    avalanche \
    arbitrum \
    optimism \
    fantom \
    starknet \
    solidity \
    alchemy \
    infura \
    etherscan \
    --upgrade

USER harambe
```

```
$ docker run --volume $HOME/.ape:/home/harambe/.ape --volume $HOME/.vvm:/home/harambe/.vvm --volume $HOME/.solcx:/home/harambe/.solcx --volume $PWD:/home/harambe/project --workdir /home/harambe/project sha256:35062e6601c03cb64d7beaec2cd96546b2d07c8f7d16ffa0b443230fe1df292d compile -f
INFO: Compiling 'string.sol'.
INFO: Compiling 'payable.sol'.
INFO: Compiling 'Token.sol'.
INFO: Compiling 'GenerativeNFT.sol'.
INFO: Compiling 'SafeMath.sol'.
```

**Comment by PoCk3T-SPAI** [comment]
@sabotagebeats thank you for that
Few thoughts:
- I'm trying to compile the smart contracts as part of the Docker image build process, so that the JSONs of my ABIs are readily available for the HTTP REST API webserver running in scripts/
- As such, the --volume mounts at runtime shouldn't impact the compilation, since I'm compiling during the Dockerfile build
- but I think that the way I use "COPY" in the Dockerfile (I don't think I included this part of my Dockerfile when commenting on Github) may interfer with the permissios of the /home/harambe/project folder and prevents `ape compile` from creating the necessary `.build` and `contracts/.cache` subfolders if I don't `chown`

**Comment by sabotagebeats** [comment]
@PoCk3T-SPAI hmm, try using the copy after you become the USER harambe, then you shouldn't need the chown?

**Comment by sabotagebeats** [comment]
@PoCk3T-SPAI I'm gonna close this issue since I haven't heard back. Please feel free to reply if this is still a problem for you but I'm going to assume this resolved your problem for now! :)
