### ISSUE TITLE
Permit2 contract causes infinite loop fetching proxy information [APE-962]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#1442]
### Environment information

- OS: linux
- Python Version: 3.10.9
- `ape` and plugin versions:

```sh
$ ape --version
0.6.8

$ ape plugins list
Installed Plugins:
  vyper        0.6.3
  alchemy      0.6.1
  etherscan    0.6.3
  template     0.6.0
  solidity     0.6.3
  foundry      0.6.7
  huff         0.1.2
```

### What went wrong?

The Permit2 implementation contract (`0x000000000022D473030F116dDEE9F6B43aC78BA3` on almost all networks) causes an infinite loop inside of our [proxy info routine](https://github.com/ApeWorX/ape/blob/main/src/ape_ethereum/ecosystem.py#L204)

### How can it be fixed?

I'm guessing that the bytecode has a matching sequence to one of the regex comparisons we are doing, so it should be required to do some additional validation on the length of the bytecode to avoid false positives

**Comment by banteg** [comment]
i've identified where the issue comes from:
1. a call to `masterCopy()` reverts
2. then ape tries to `get_virtual_machine_error ` of a not yet initialized contract.
3. which in turn calls `enrich_error`, which [tries to get the abi](https://github.com/ApeWorX/ape/blob/84b276eff63734f32640f52f87f3b778f6c81eb3/src/ape/managers/compilers.py#L243), so it falls into the inifinite loop.

the solution could be to either propagate `skip_trace=True` up to `enrich_error` or better not try getting partially-initialized abis from the error handler.
