### ISSUE TITLE
required package at start

### ISSUE THREAD

**Issue by benjyz** [ApeWorX/ape#155]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.1.0a23

$ ape plugins list
INFO: No plugins installed
```

* Python Version: 3.9.5
* OS: osx

### What went wrong?

running ape compile gives
WARNING: Error loading plugin package 'ape_ethereum'

trying to add this package

```
ape plugins add ethereum
WARNING: duplicate pkg_name 'ape'
WARNING: Error loading plugin package 'ape_ethereum'
WARNING: $GITHUB_ACCESS_TOKEN not set, skipping 2nd class plugins
ERROR: Cannot add 1st class plugin 'ape_ethereum'
```

but according to package list there are no package installed

**Comment by fubuloubu** [comment]
That's fair, I don't think we display the 1st class plugins, but that's an easy fix

**Comment by unparalleled-js** [comment]
The first class plugins get displayed if you pass `--all` 

Maybe the best solution here is to change some error messages.

1. When a 1st class plugin does not load right, the whole program should bomb out instead of silently passing (the silently passing is great for 2nd and 3rd party plugins but not 1st class plugins because that is probably an ape-developer's fault)
2. When trying to install a 1st class plugin, we should have a more specific error for it being a 1st class plugin, like `"ERROR: attempting to install first-class plugin ape-Ethereum"`

**Comment by unparalleled-js** [comment]
Step 2 of this is already done! Working on step 1 now..
