### ISSUE TITLE
bug: BaseModel error: AttributeError: 'super' object has no attribute '__getattr__'

### ISSUE THREAD

**Issue by mikeshultz** [ApeWorX/ape#1736]
### Environment information

- OS: linux
- Python Version: 3.10.13
- `ape` and plugin versions:

```sh
$ ape --version
0.6.25

$ ape plugins list
# ...copy and paste result of above command here...
```

**NOTE**: unable to provide the last one due to another (probably unrelated?) error in plugin iteration.

### What went wrong?

Accessing non-ape or model props on `BaseModel` results in an `AttributeError`.  Here's an repro example:

```python
from ape.utils.basemodel import BaseModel


class MyModel(BaseModel):
    foo: str
    bar: int


m = MyModel(foo="abc", bar=123)
print("dump:", m.model_dump())
```

And raises the following:

```
Traceback (most recent call last):
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/ape/utils/basemodel.py", line 206, in __getattr__
    return super().__getattr__(name)
AttributeError: 'super' object has no attribute '__getattr__'. Did you mean: '__setattr__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/dev/silverback/model_test.py", line 10, in <module>
    print("dump:", m.model_dump())
  File "/home/mike/.venvs/ape-test/lib/python3.10/site-packages/ape/utils/basemodel.py", line 227, in __getattr__
    raise ApeAttributeError(message)
ape.exceptions.ApeAttributeError: 'MyModel(foo='abc', bar=123)' has no attribute 'model_dump'
```

This occurs on both Pydantic v1 and v2.

Interestingly, `m.dict()` does work.  Presumably because `__getattr__()` is never called?  I'm not entirely sure.

### How can it be fixed?

I'm not entirely sure, maybe `__getattr__()` shouldn't exist on Ape's `BaseModel`.  It seems that `__getattr__()` [was removed from `BaseModel` back in v0.32](https://github.com/pydantic/pydantic/pull/712).

@antazoey thoughts?

**Comment by antazoey** [comment]
Just a note: `model_dump()` is NOT available on v1 so an AttributeError seems expected in that case.
I do notice that there is no super().__getattr__() though so that part can be reworked a little but I don't think it is causing any issues?

I guess I am a little confused on the main problem you are facing. `dict()` should work on v1 and for v2 proper you need to call `model_dump()`. If you are using v1 back imports, you must call dict().

Look at this PR for "proper" v2: https://github.com/ApeWorX/ape/pull/1674/files, it used `model_dump()` all over and it works because we are not using the v1 back imports anymore.

I am guessing you are trying to use v2 syntax on v1 back imports which is still pydantic v2 and perhaps that is why you are having issues. Use `dict()`!

**Comment by antazoey** [comment]
OK - I noticed now you don't have control of where this gets called so in your case, you are unable to use pydantic v2 because Ape does not properly support it. It should soon though, as part of 0.7.
