### ISSUE TITLE
Allow an easy way to disable automatic etherscan fetching when instanciating a Contract()

### ISSUE THREAD

**Issue by Rozengarden** [ApeWorX/ape#1939]
### Overview

When creating a new contract instance via an address with the etherscan plugin installed additionals information such as abi are fetched on etherscan automagicaly (which is a really great feature). 

However it looks like there is no way to disable this behaviour even when providing most of the infomations myself apart from directly uninstalling the etherscan plugin.

### Specification

I don't see an easy way to implement this that doesn't involve footgun

### Dependencies

I don't believe there are dependencies for this feature

**Comment by fubuloubu** [comment]
so, `Contract` excepts either a `contract_type=...` or an `abi=...` kwarg, which should bypass calling out to etherscan in order to fetch the contract type. further, if you have already downloaded the contract type, it should simply use the cached copy instead of calling out as well.

do you feel like this is not the case? does those kwargs help you for your use case?

**Comment by antazoey** [comment]
fixed by #2401
