### ISSUE TITLE
Support call traces on reverted txns

### ISSUE THREAD

**Issue by fp-crypto** [ApeWorX/ape#1945]
### Overview

At present, reverted txns do not provide a call trace. This functionality would be invaluable.

### Dependencies

**Comment by mikeshultz** [comment]
Couple clarifying questions here:

- Which network and provider are you using?  
- What behavior were you expecting from Ape?

Digging into this issue today, I found something that might be what you were looking for. Would this suit your needs?

```python
from ape.exceptions import ContractLogicError
try:
    # My test contract call that reverts
    contract.revertExtern(True, sender=deployer)
except ContractLogicError as err:
    err.txn.show_trace()
    raise
```

This should give you an output something like this:

```
Call trace for '0xd0cb99a4fd37ae95c67d789cc3aa6f55b2ceb217e013dee3651614ba2f34455c'
reverted with message: "revertCall"
tx.origin=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Reverter.revertExtern(go=True) -> <?> [27675 gas]
└── 0xa16E02E87b7454126E5E10d957A927A7F5B5d2be.0x3381f788(0x0000000000000000000000000000000000000000
    000000000000000000000001) -> 
    0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000
    00000000000000000000000000000000000000000a72657665727443616c6c0000000000000000000000000000000000
    0000000000 [354 gas]
```

I don't think this functionality is obvious.  It's something I just found when digging into this report.  Definitely some room for improvement here either in the API or in documentation at least.

**Comment by fubuloubu** [comment]
was thinking a flag `ignore_revert=True` would be handy here for several use cases:

```py
from ape_ethereum import TransactionStatusEnum

tx = contract.revertExtern(True, sender=deployer, ignore_revert=True)  # skips `tx.raise_for_status()`
assert tx.status is TransactionStatusEnum.NO_ERROR, tx.show_trace()
# OR
breakpoint()  # check stuff off of `tx` manually before resuming
# OR just always proceeded despite a failure
```

**Comment by fubuloubu** [comment]
It should probably show traces without `ignore_revert` set as the default behavior, but one nice thing about the override flag ignoring that behavior is we have a workaround in case it is broken

**Comment by mikeshultz** [comment]
Alright, so traces should print to console on every revert regardless.  Will put something together.

IMO, instead of a logic branch with `ignore_revert`, maybe we shouldn't raise an exception at all.  A revert is still a "valid" result of a transaction and arguably not an error state.  Or at least not an error in and of the framework.  That seems like a breaking change for later though.

**Comment by mikeshultz** [comment]
Got a few PRs up for this, since most providers seem to implement error handling slightly differently.  Let me know if I missed any provider plugins that could also use this treatment.

- https://github.com/ApeWorX/ape/pull/1949
- https://github.com/ApeWorX/ape-foundry/pull/92
- https://github.com/ApeWorX/ape-hardhat/pull/164

Plugin PRs are still WIP due to test failures (likely unrelated CI issues) that I still need to deal with.
