### ISSUE TITLE
feat: Add option to explicitly ignore reverts 

### ISSUE THREAD

**Issue by Aviksaikat** [ApeWorX/ape#2180]
### Overview

Provide a simple overview of what you wish to see added. Please include:

- Add an option like brownie to explicitly ignore reverts like brownie does with `allow_revert=True` option
-  Would be a great feature idea, and something to consider further for "smart receipts" we want to add to v1 (e.g. blocking or non-blocking receipt handling based on how you call a transaction and work with the receipt) (- @fubuloubu via discord)

### Specification

N/A

### Dependencies

N/A

**Comment by fubuloubu** [comment]
We should add `revert_on_fail=False` as a new kwarg to contract transactions, which in the case of a failure would log a warning instead of raise an error, and ensure that `ReceiptAPI` has `.error` property so it's there in case a failure did occur and you want to access it or do instance checks against it (e.g. `if isinstance(tx.error, contract.CustomError): ...`).

**Comment by antazoey** [comment]
I think `revert_on_fail` may imply something inaccurate... `revert_on_fail` makes me sound like somehow we are able to make the VM not revert at all and let it crash out some other way.

I think `raise_on_revert` or something alike is more accurate

**Comment by antazoey** [comment]
I like `allow_revert` as well because it mimics `click`'s `allow_failure` flag in their test-runner invoke.
