### ISSUE TITLE
Caching: Deployment Map

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#374]
### Overview

It is a bit of hurdle trying to figure out how to manage and share deployment addresses for projects. This way, we can run automations from team-mate to team-mate.

### Specification

Similar to this feature in brownie: https://eth-brownie.readthedocs.io/en/stable/deploy.html#the-deployment-map

For sharing, maybe we could have config items automatically populate the deployment map. (Does brownie do this?)

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
You could have it populate items in the `ape-config.yaml` that could be used in a script to give access to these addresses in a much faster way in order to load your contract system fast

note that ethPM has support for these keys (not in the most streamlined way)

**Comment by unparalleled-js** [comment]
> You could have it populate items in the `ape-config.yaml` that could be used in a script to give access to these addresses in a much faster way in order to load your contract system fast
> 
> note that ethPM has support for these keys (not in the most streamlined way)

Would `ape` be changing the `ape-config.yaml` or would my script?

**Comment by unparalleled-js** [comment]
Right now, I just have a script that creates a `map.json` file which is controlled in `git`.

**Comment by fubuloubu** [comment]
> > You could have it populate items in the `ape-config.yaml` that could be used in a script to give access to these addresses in a much faster way in order to load your contract system fast
> > 
> > note that ethPM has support for these keys (not in the most streamlined way)
> 
> Would `ape` be changing the `ape-config.yaml` or would my script?

Ape shouldn't change the config, mutable Co fig osunds awful. However, we could read those keys and load those contracts at the given addresses very easily. For a deployed project, it tends not to change very often e.g. Yearn Vaults has a registry that indexes all the vaults, I just need the address of the registry available on every deployed network/ecosystem

**Comment by unparalleled-js** [comment]
Okay, yes I thought so, but was just making sure.
So in essence, this feature has two parts:

1. Allow the user to set addresses in the config file and allow them to access / initialize `ContractInstance`s of those addresses
2. Cache active deployments (in `.build` directory?) and also allow user to create `ContractInstance`s of those.

I am trying to think of syntax for this:

```python
my_contract = project.MyContract.at(-1)
```

where `-1` indicates the latest (most recent) deployment, including both the config file and active ones.

Else, we can have like a map in the config file?

```python
contract_address = config.get_config("deployments").token_v2
token_v2 = project.My
```

___

Or what were you thinking as far as syntax goes?

**Comment by unparalleled-js** [comment]
Oh wow I just noticed that `deployments` is already part of the `PackageManifest`

**Comment by fubuloubu** [comment]
> Okay, yes I thought so, but was just making sure. So in essence, this feature has two parts:
> 
> 1. Allow the user to set addresses in the config file and allow them to access / initialize `ContractInstance`s of those addresses
> 2. Cache active deployments (in `.build` directory?) and also allow user to create `ContractInstance`s of those.

Yes, this sounds right!

---

> I am trying to think of syntax for this:
> 
> ```python
> my_contract = project.MyContract.at(-1)
> ```
> 
> where `-1` indicates the latest (most recent) deployment (via checking block number), including both the config file and active ones.
> 

Don't think this is really at all very explicit. We've talked about the `chain` manager (#129), perhaps it could contain a set of deployed objects, indexable by `ContractContainer` objects from `project`/`ProjectManager`:

```py
my_contract = project.MyContract.at(
    chain.contracts[project.MyContract][-1]   # e.g. "Last deployed `project.MyContract` contract type"
)
```

---

> 
> Else, we can have like a map in the config file?
> 
> ```python
> contract_address = config.get_config("deployments").token_v2
> token_v2 = project.TokenV2.at(contract_address)
> ```
> 
> Or what were you thinking as far as syntax goes?

As you already noted: 

> Oh wow I just noticed that `deployments` is already part of the `PackageManifest`

So we can just do:

```py
token_v2 = project.TokenV2.at(
    project.deployments.ethereum.mainnet[project.TokenV2]
    # deployment address of `project.TokenV2` contract type on Ethereum Mainnet
)
```

And this via the config file:

```yaml
...

deployments:
  ethereum:
    mainnet:
      TokenV2: 0x....
```

Although this is one area where I think EIP-2678 is not necessarily the best at working with, because it indexes deployments by BIP122 URIs and contract aliases (which are confusingly not the same as contract types)

**Comment by unparalleled-js** [comment]
It not immediately clear to me how `chain_manager` would get its `contracts`. Are those from the `config`, the ones that have deployed locally using ape, or does it use `ape-etherscan` somehow, or all 3?

**Comment by fubuloubu** [comment]
> It not immediately clear to me how `chain_manager` would get its `contracts`. Are those from the `config`, the ones that have been deployed locally using ape, or does it use `ape-etherscan` somehow, or all 3?

Cached during session. Probably indexed by bytecode hash.

So, imagine I made a deployment of `project.TokenV2` in my current session. I would store that deployment via:
```py
c: ContractInstance = project.TokenV2.deploy(...)

deployments[ecosystem][network][c._contract_type.deployment_codehash].append(c)
```

Later on, either within this current session, or in a new one, I could retrieve the list of deployments for a given contract type (at a specific code configuration) via it's `deployment_codehash` by doing:
```py
deployments[ecosystem][network][project.TokenV2.deployment_codehash]
```

NOTE: `ContractType` currently does not have a `.deployment_codehash` member, but could easily be added as `deployment_codehash = keccak256(contract_type.deployment_bytecode)` (should not use `runtime_bytecode` because that doesn't account for changes made in the constructor).

NOTE: It is important to also know the "deployment arguments" for the deployment, in order to determine it's initial configuration, which should be stored in the caching structure when `ContractInstance` is serialized to disk (probably along with the `txn_hash` and other useful parameters for indexing a deployment)

**Comment by unparalleled-js** [comment]
Oh I see, so the user has to explicitly store the deployment in the manifest. That actually clears everything up, thanks!

**Comment by fubuloubu** [comment]
The config file would be a preset list of deployments that are auto-populated into the project when it connects to a specific network, to reduce the time needed to load a complete system.

Perhaps the config file should be modified from the above as follows:

```yaml
...

deployments:
  ethereum:
    mainnet:
      - contract_type: TokenV2  # Could this allow referencing dependencies' contracts? e.g. `yearn.Registry`
        address: 0x....
        # Other keys might be useful e.g. `type: EIP1167Proxy`
```

**Comment by unparalleled-js** [comment]
What is the main reason for not wanting that to happen automatically? Maybe not manifest-based deployments, but is there any reason to refrain from just always caching session deployments?

**Comment by fubuloubu** [comment]
> Oh I see, so the user has to explicitly store the deployment in the manifest. That actually clears everything up, thanks!

Actually was describing a system that caches under-the-hood, since it's hard to find contract deployments without an indexing service (e.g. Etherscan), this might fit in more with the ideas behind the `CacheAPI` middleware stuff (we've talked about this at length, let's continue this discussion during planning session tomorrow?)

**Comment by fubuloubu** [comment]
I think there's two different concepts we're talking about here, general caching of deployments, and specific deployment addresses that are "important" to the system, e.g. "finalized" deployments for a project

**Comment by unparalleled-js** [comment]
I am so confused by this ticket.

I want all locally deployed contracts cached because we need it for testing purposes (coverage, etc.). I don't care about publishing right now or live networks.

**Comment by unparalleled-js** [comment]
Closing as this was done a while ago (the config portion anyway)

**Comment by unparalleled-js** [comment]
also was maybe a duplicate of this https://github.com/ApeWorX/ape/issues/530

The original feature I wanted is now described in the ticket above
