### ISSUE TITLE
Proposition: Allow unimplemented API methods to raise instead of failing to register plugin

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#397]
### Elevator pitch:

Adding a new API method should be a complete breaking-change to plugin implementation classes. Instead, we should raise `NotImplementedError()` by default.

### Value:

Let's say I want to add new functionality to the `ExplorerAPI`, `get_account_transactions()`.  Now, existing explorer plugins, such as `ape-etherscan`, fail to even register until we implement this new method even though all of its existing functionality works just fine. By allowing the plugin to register and work (and just raise `NotImplementedError()`, we are breaking plugins **less**. We can still update the plugin as soon as we can but this will allow it to still work in the meantime. We could even include in the `NotImplementedError()` something like `Try updating the plugin to a newer version that has implemented this method` or something.

### Dependencies:
none

### Design approach:

Some sort of clean way that makes abstractmethods raise `NotImplemented` by default.
Perhaps we wrap the existing `abstractmethod` into our own?

*NOTE**: This is just a proposition because I don't think adding a method should be a breaking change. Perhaps there are downsides to this, such as it not being obvious when something needs to get updated. Thoughts?

### Task list:

* [ ] Tasks go here

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
> This is just a proposition because I don't think adding a method should be a breaking change.

Well, this is something to discuss! I think that when you are not working with the expected interface, it is important not to load the plugin because it could work incorrectly or not have the right features to work.

In general, I think identifying api methods as "required" (e.g. does not load the plugin) vs. "preferred" (e.g. plugin should still load, but that feature is not available) is an important distinction to make, so we can make sure the right outcomes occur.

This is a good thing to figure out before we do a full release, because then the versioning schema matters e.g. if "breaking" changes only happen in Major releases (TBD), then having a new release of Ape core adding an api method that is "required" is fine, because it is known that breaking changes might occur. In that vein, perhaps with Minor releases (TBD) there might be a mandate that new api methods cannot be introduced where they are "required" by default.

**Comment by unparalleled-js** [comment]
We already have good separation here - if an API method is not really required, we can just not make it abstract and make it either return `NotImplentedError()` or return `None` or whatever. We do this in several places already (looking at EIP-1559 stuff).

So on that note, I will close this as WON'T DO.
