### ISSUE TITLE
Explore using importlib's SourceFileLoader for scripts

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#517]
### Overview

Looking at how `Nile` runs scripts: https://github.com/OpenZeppelin/nile/blob/main/src/nile/core/run.py
It seems really simple and elegant because they use something from importlib.

Spike: Are we able to make our script loading functionality a lot simpler using the same?

### Specification

```python
from importlib.machinery import SourceFileLoader

script = SourceFileLoader("script", path).load_module()
script.run()
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by fubuloubu** [comment]
This is basically what we do, but with `main()`

https://github.com/ApeWorX/ape/blob/56049f6a0580aeafb21509dd3de9f70b7a49a19d/src/ape/managers/project.py#L672

**Comment by fubuloubu** [comment]
Made a big change to how this works in #522

First, the module is compiled to look for any relevant hook points (but does not execute loading yet):
https://github.com/ApeWorX/ape/pull/522/files#diff-eeb99062ddc309013af731cfad8f19beb2dcd0fa4e02cd6a38cc9a0c19f90a42R31

Then, if the right hook points are located:
https://github.com/ApeWorX/ape/pull/522/files#diff-eeb99062ddc309013af731cfad8f19beb2dcd0fa4e02cd6a38cc9a0c19f90a42R37

We return a click command (or group, if upstream) and compose the commands together so that they are all registrered if you do `ape run --help`:
https://github.com/ApeWorX/ape/pull/522/files#diff-eeb99062ddc309013af731cfad8f19beb2dcd0fa4e02cd6a38cc9a0c19f90a42R105

**Comment by fubuloubu** [comment]
so, using `SourceFileLoader` fails to work with relative imports:

```bash
$ ape --verbosity DEBUG run deploy
DEBUG: Parsing module: scripts/deploy.py
DEBUG: Found 'main' method in script: scripts/deploy.py
ERROR: Exception while loading script: scripts/deploy.py
        ImportError: attempted relative import with no known parent package
        (Use `--verbosity DEBUG` to see full stack-trace)
DEBUG: Traceback (most recent call last):
  File "ape/src/ape_run/_cli.py", line 30, in __load_module
    return SourceFileLoader("script", str(filepath)).load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "ape/tests/integration/cli/projects/script/scripts/deploy.py", line 4, in <module>
    from ._utils import deploy  # noqa: F401
ImportError: attempted relative import with no known parent package
```

But at least the error message is better here :shrug:

**Comment by fubuloubu** [comment]
closed by https://github.com/ApeWorX/ape/pull/522
