### ISSUE TITLE
add get_version_map to ape-vyper plugin

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#850]
### Overview

` cls.compiler_manager.registered_compilers['.vy'].get_version_map(source_paths)` doesn't work on vyper because vyper plugin doesn't have `get_version_map()`

* What you are trying to do
get version map from vyper
* Why Ape's current functionality is inadequate to address your goal
doesn't have version map for vyper

### Specification

Describe the syntax and semantics of how you would like to see this feature implemented. The more detailed the better!

Remember, your feature is much more likely to be included if it does not involve any breaking changes.

should be in the plugin

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
We should probably make `get_version_map` an API method if it isn't already

**Comment by sabotagebeats** [comment]
> We should probably make `get_version_map` an API method if it isn't already

`get_version_map` works on solidity but it throws an error it doesn't exist in vyper

**Comment by unparalleled-js** [comment]
@sabotagebeats  `get_version_map` is more of an implementation detail in the Solidity plugin for other features, that is why its not in ape-vyper. It is not part of the Compiler API so it is not necessarily expected to be implemented. However, you need this functionality, so there is an argument to add it to `CompilerAPI`.

Otherwise, from a plugin perspective, all you need to do is create a JSON file in the build directory, it does really matter how you do it. It may look different from compiler to compiler.

**Comment by sabotagebeats** [comment]
haven't started

**Comment by unparalleled-js** [comment]
- [ ] Decide if is needed or what adjustments are necessary

**Comment by unparalleled-js** [comment]
Not needed!
