### ISSUE TITLE
Show uncaught VirtualMachineError / TransactionError revert lines

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape#867]
### Overview

Intercept stack trace during unhandled VirtualMachineError or TransactionError and show only the line of revert, 

### Specification

![brvt](https://user-images.githubusercontent.com/19540978/178281328-49cab1d5-a6f6-44d4-b07b-b5bad84b0fd5.jpg)

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by unparalleled-js** [comment]
@banteg What is all needed to start development on this?  Do we need the coverage-setup or anything else with tracing support first?

Also, is there anything else we should know about this ticket before beginning development?

**Comment by fubuloubu** [comment]
> @banteg What is all needed to start development on this? Do we need the coverage-setup or anything else with tracing support first?
> 
> Also, is there anything else we should know about this ticket before beginning development?

You need sourcemapping and/or ast layout and/or Vyper's error map to find the PC that a revert corresponds to, and the source code that maps to whatever the program counter of the revert is

@helloibis is investigating some of this

**Comment by helloibis** [comment]
@unparalleled-js @fubuloubu what I've uncovered a bit of as part of the other ticket is that often times we'll have `VirtualMachineError` or `TransactionError` exceptions that arise before the transaction is actually committed. In such cases, it doesn't seem like I can actually get a stack trace (even if I do have a `txn_hash`). One example is the issue I posted in the Discord where I was unable to deploy a contract due to insufficient gas, the trace info just comes up empty.

Should we consider this feature something that is only shown if we can access the trace info (for instance it seems we can always do it for `ContractLogicError`), and otherwise doesn't show additional information?

cc @NotPeopling2day

**Comment by fubuloubu** [comment]
> Should we consider this feature something that is only shown if we can access the trace info (for instance it seems we can always do it for `ContractLogicError`), and otherwise doesn't show additional information?

I think this makes sense, or at least if we can start here and figure out something over time for the other exception types it'll work

**Comment by helloibis** [comment]
Status update: I'm not sure if this ticket is necessarily blocked, but definitely after https://github.com/ApeWorX/ape/issues/937 is completed this should be easier to implement and work in all `TransactionError` cases (other than `OutOfGasError` of course)
