### ISSUE TITLE
`ape plugins install` from tag, branch, repo, or pull request

### ISSUE THREAD

**Issue by banteg** [ApeWorX/ape#896]
### Overview

[foundryup](https://github.com/foundry-rs/foundry/tree/master/foundryup) has a very handy functionality which allows installing a version from a branch, a tag, a forked repo, or a pull request. this could be a nice shorthand for ape plugins, so i could say something like `ape plugins install etherscan --pr 42`.

### Specification
add `--tag`, `--pr`, `--branch`, `--repo` options to `ape plugins install` which would install a version from source instead of from pypi.

### Dependencies
i think this can be handled by pip alone, since it supports `git` protocol.

**Comment by fubuloubu** [comment]
Foundry needs this, because it's simply not possible otherwise to hack in functionality into the binary without recompiling it, but `pip` is dynamic, and I think anyone competent who is contributing or using un-released code should understand they can do anything they want to to their environment with pip. It's a few extra steps for them, but I think this feature would be a lot more trouble than it's worth to provide. `ape plugins` is a streamlined wrapper around `pip` intended only for production-supported plugins.

We could definitely add a little clarity to the contributing docs to inform people that there are many ways of using `pip` to achieve the desired result
