### ISSUE TITLE
Local ape version uses whatever tag is latest [APE-114]

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#90]
**Just keeping this around as a notice**

You might run into issues where you have a local install and are trying to work with a plugin pinned to a specific version.

While the code might be correct, the version will be off because of how `setuptools-scm` uses git tags to generate the latest version.

The easy solution to this is simple fetch the tags via `git fetch upstream --tags` and reinstall via `pip install .`. You will then have the correct version

**Comment by unparalleled-js** [comment]
I can't see this notice getting read too much since it is hidden in the backlog of issues.

I think a note like this belongs in the `CONTRIBUTING.md` guide. Reason: Contributors are typically the people who do local installs and thus this message mostly caters to them. They probably are more like to read a contributing guide (I hope) then to stumble on this issue.

^ If we agree on that, let's convert this issue to a ticket item (remove the `wontfix`) and get this note in a spot where people will see it

**Comment by fubuloubu** [comment]
What if we just pinned the issue?
